name: parallax

channels:
  - conda-forge
  - defaults

dependencies:
  - git
  - python=3.8
  - pyqt>=5.15
  - pip
  - scipy
  - pyserial
  - pip:
    - pyqtgraph
    - opencv-python-headless
    - spinnaker-python
    - PyOpenGL
    - zaber-motion
    - git+https://github.com/campagnola/coorx
    - git+https://github.com/AllenNeuralDynamics/python-newscale@calibration
    - git+https://github.com/AllenNeuralDynamics/mis-focus-controller-sw

