name: parallax

channels:
  - conda-forge
  - defaults

dependencies:
  - git
  - python=3.8
  - pip
  - scipy
  - pyserial
  - cudnn=8.2.1
  - pip:
    - PyQt5>=5.15
    - pyqtgraph
    - opencv-python-headless
    - spinnaker-python
    - PyOpenGL
    - zaber-motion
    - git+https://github.com/chronopoulos/coorx
    - git+https://github.com/AllenNeuralDynamics/python-newscale@axes-on-target
    - git+https://github.com/AllenNeuralDynamics/mis-focus-controller-sw
    - protobuf==3.20.1
    - sleap==1.3.0

