[tool.poetry]
name = "parallax"
version = "0.1.0"
description = "GUI software for photogrammetry-assisted probe targeting in electrophysiology"
authors = ["Hanna Lee <hanna.lee@alleninstitute.org>"]
license = "Allen Institute Software License"
readme = "README.md"
homepage = "https://github.com/AllenNeuralDynamics/parallax"
repository = "https://github.com/AllenNeuralDynamics/parallax"
documentation = "https://github.com/AllenNeuralDynamics/parallax/wiki"
keywords = ["parallax"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
]
requires-python = ">=3.8"

[tool.poetry.dependencies]
python = "^3.8"
pip = "*"
PyQt5 = ">=5.15"
pyqtgraph = "*"
opencv-python-headless = "*"
opencv-python = "4.5.1.48"
spinnaker-python = "*"
PyOpenGL = "*"
zaber-motion = "*"
typing-extensions = "*"
protobuf = "3.20.1"
sleap = "1.3.0"
pyserial = "*"
coorx = { git = "https://github.com/chronopoulos/coorx" }
newscale = { git = "https://github.com/AllenNeuralDynamics/python-newscale", branch = "axes-on-target" }
mis_focus_controller = { git = "https://github.com/AllenNeuralDynamics/mis-focus-controller-sw" }

[tool.poetry.dev-dependencies]
flake8 = "*"
pytest = "*"
coverage = "*"
interrogate = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
