[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"
 
[project]
name = "parallax"
description = "GUI software for photogrammetry-assisted probe targeting in electrophysiology"
license =  {text = "Allen Institute Software License"}
readme = "README.md"
keywords = ["parallax"]
dynamic = ["version"]
requires-python = "~=3.8"
classifiers = [
    "Programming Language :: Python :: 3"
]
 
dependencies = [
    "pip",
    "PyQt5>=5.15",
    "pyqtgraph",
    "opencv-python-headless",
    "opencv-python",
    "spinnaker-python", 
    "scipy",
    "pandas",
    "scikit-image",
    "requests"
   ]
 
[tool.setuptools.packages.find]
where = ["parallax"]
 
[tool.setuptools.dynamic]
version = {attr = "parallax.__version__"}
readme = {file = "README.md"}
 
[project.optional-dependencies]
linters = [
    'codespell',
    'coverage',
    'flake8',
    'interrogate',
    'isort'
]
 
[tool.interrogate]
exclude = ["setup.py"]
fail-under = 100
 
[tool.codespell]
skip = ".git,*.json"
 
[tool]
homepage = "https://github.com/AllenNeuralDynamics/parallax"
repository = "https://github.com/AllenNeuralDynamics/parallax"
documentation = "https://github.com/AllenNeuralDynamics/parallax/wiki"